[package]
name = "serial-reader"
version = "0.1.0"
authors = ["Egor <steammycss@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport="^4.0.0"
ansi_term = "^0.12.1"